### PR TITLE
WIP: Typescript spike

### PR DESCRIPTION
**Pull request by ethanfrey**
Try to gradually move pieces from mjs to typescript.

* Set up `ts` directory next to `src` directory with same structure
* On build, copy `src` to `build` and then use `tsc` to compile contents of `ts` dir on top (merge them as js)
* Webpack now builds from `build`, the combined generated js

Current status:
- [x] tsc compiles
- [x] merge ts and mjs in webpack build successfully
- [x] iov-wallet `yarn dev` working

Update: `src` contains hand-coded `*.mjs` as well as auto-generated `*.js`, `*.d.ts` and `*.js.map` from the `ts` package. This replaces the `build` directory and allows this to play nicely with `yarn dev` from iov-wallet that pulls from `src`

### CODE REVIEW

**Comment by rudi-cilibrasi** [comment]
i would prefer we wait for https://github.com/Microsoft/TypeScript/issues/18442 before we do this

**Comment by ethanfrey** [comment]
Okay, it now just inserts the typescript into the src directory alongside mjs and it works fine with iov-wallet.

I know mjs enforces strictness, but ts enforces even more, so the generated js has been checked beforehand. Not sure why #18442 is so important, as long as the ts->js files and the mjs files interoperate without problems. I mean, longer-term would be to migrate all code to typescript, so there would be no hand-coded mjs.

**Comment by rudi-cilibrasi** [comment]
i don't really understand what you mean when you say "migrate from/to .mjs"

to me, `.mjs` is a solution to a problem you are recreating in your usage of the vague old `.js` term that `.ts` inherits.

**Comment by rudi-cilibrasi** [comment]
also i wanted to let you know it's probably worth considering updating `browsedown` so that it is `.mjs` compatible; you can see that it's inconvenient to include currently that's why i need to make a bridge file. `.mjs` is considered an upgrade that's why newer versions of node and webpack support it and it is seemingly a necessary step to unify the javascript ecosystem by clarifying a certain complete and strict set of assumptions that include a lack of configurability in certain strategic areas. i'm afraid you are configuring those areas in the proposal but can't tell for sure.

**Comment by rudi-cilibrasi** [comment]
closing until reconsidered, vetted by Rudi+Isabella+Ethan and conflicts removed

**Pull request closed without merging**
