### PR TITLE
remove vague selectors

### PR DESCRIPTION
**Pull request by rudi-cilibrasi**
can you please help to clear up these error visible from
`yarn run build` @ethanfrey  ? they are all related to renaming / selecting switching from old to new.
also visible in travis ci

all these selectors are classified as _vague_ based on the fact that their names do not start with one of the standard 4 new prefixes: `transient`, `blockchain`, `purseNonSense`, `purseSense` and in many cases they don't even end in `Selector`

### CODE REVIEW

**Comment by rudi-cilibrasi** [comment]
once we have names for keyrings and identities from the updated `iov-core` (or we mock them) i can help you put in the missing reducers to finish this

**Comment by rudi-cilibrasi** [comment]
also it's ok to use this PR as just a "todo list" of stuff to remove and instead do it in a series of smaller pr's if that's easier.

**Comment by ethanfrey** [comment]
Okay, I will cleanup, rebase on other PR, and cleanup again :)

One comment, the whole import/export chain in `index.mjs` is easier in typescript.
You can simply type `export * from './chainIds';` for example and it will import all exported variables and re-export. I don't know if there is such a feature in mjs, but it is quite nice when you just want to combine the public exports of a bunch of files and re-export them.

https://github.com/iov-one/iov-core/blob/master/packages/iov-tendermint-types/src/index.ts

Other times, you only want to export part and the name by name approach is indeed necessary.

**Comment by ethanfrey** [comment]
On second look, most of the broken stuff isn't just renames or bad imports, but rather that the requested functionality is no longer exposed by other parts.

To fix this properly would be a macro-pr with all desired cleanup. I would rather keep it as a reminder of where it needs to go and make a few other prs to get there

**Pull request closed without merging**
